name:                real-world-haskell
version:             0.1.0.0
github:              "adispring/real-world-haskell"
license:             BSD3
author:              "wangzengdi"
maintainer:          "sunnyadi@163.com"
copyright:           "wangzengdi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adispring/real-world-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src/
    - src/ch05

executables:
  real-world-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell

tests:
  real-world-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell
